import { Container, Typography } from '@mui/material'
import Footer from '../layout/Footer'
import PrivacyHeader from '../layout/PrivacyHeader'
import Layout from '../layout/layout'

function Privacy() {
  return (
    <>
    <PrivacyHeader />
      <Container sx={{ pt: '2em', pb: '1em', width: '50%', pb: '5em', textAlign: 'center'}}>
        <Typography variant="h2" sx={{ textAlign: 'center' }}>
          Privacy Policy
        </Typography>
        <Typography variant='body1' sx={{ pt: '1em', fontSize: '14pt' }}>
          Your privacy is important to us. It is TT Web Development &amp;
          Design's policy to respect your privacy regarding any information we
          may collect from you across our website,
          <a href="https://trevorstanner.com">https://trevorstanner.com</a>, and
          other sites we own and operate. We only ask for personal information
          when we truly need it to provide a service to you. We collect it by
          fair and lawful means, with your knowledge and consent. We also let
          you know why we’re collecting it and how it will be used. We only
          retain collected information for as long as necessary to provide you
          with your requested service. What data we store, we’ll protect within
          commercially acceptable means to prevent loss and theft, as well as
          unauthorized access, disclosure, copying, use or modification. We
          don’t share any personally identifying information publicly or with
          third-parties, except when required to by law. Our website may link to
          external sites that are not operated by us. Please be aware that we
          have no control over the content and practices of these sites, and
          cannot accept responsibility or liability for their respective privacy
          policies. You are free to refuse our request for your personal
          information, with the understanding that we may be unable to provide
          you with some of your desired services. Your continued use of our
          website will be regarded as acceptance of our practices around privacy
          and personal information. If you have any questions about how we
          handle user data and personal information, feel free to contact us.
          </Typography>
          <Typography variant='body1' sx={{ pt: '1.5em', fontSize: '14pt', pb: '1em' }}>
          This policy is effective as of December 7th, 2019. 
          </Typography>
          <Typography variant='body1' sx={{ pt: '.5em', fontSize: '14pt' }}>
        Generated by
          <a
            title="Privacy Policy Template Generator"
            href="https://getterms.io/"
          >
            GetTerms.io
          </a>
        </Typography>
      </Container>
    <Footer />
    </>
  )
}

export default Privacy
